const actionTypes = {
  LOGIN: "LOGIN",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT: "LOGOUT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  // USER
  GET_CURRENT: "GET_CURRENT",
  GET_ALLUSERS: "GET_ALLUSERS",
  GET_CUSTOMERS: "GET_CUSTOMERS",
  GET_ALLCUSTOMERS: "GET_ALLCUSTOMERS",

  // PROJECT
  GET_PROJECTS_USER: "GET_PROJECTS_USER",
  GET_PROJECTS_PROGRESS: "GET_PROJECTS_PROGRESS",
  GET_ALLPROJECTS: "GET_ALLPROJECTS",
};

export default actionTypes